version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000
# actions are like functions, ran in CLI using 'run' command
actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  generate_report:
    run: python:v2 python analysis/report.py
    needs: [generate_dataset] # this action depends on output of 'generate_dataset' action
    outputs:
      moderately_sensitive: # may be publicly released after review
        chart: output/report.png
